baseurl = "http://localhost:1313/"
languageCode = "en-us"
uglyurls = true
relativeURLs = true
title = "Go语言学习笔记"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
preserveTaxonomyNames = true
disablePathToLower = true

# Enable Google Analytics by entering your tracking id
googleAnalytics = "c7442f5794ea2abb71c6ff05dc0b8779"

[params]
	# General information
	author = "敖小剑"
	keywords = "go,golang,学习笔记,敖小剑"
	description = "Go 语言学习笔记。"
	copyright = "版权所有，转载请注明出处"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/skyao/learning-go"
	
	version = ""
	logo = "images/logo.png"
	favicon = ""
	
	permalink = "#"
	
	# reward button, comment this to disable it
	reward = true
	
	# Custom assets
	custom_css = []
	custom_js  = []
	
	# Syntax highlighting theme
	highlight_css  = ""
	
	[params.palette]
		primary = "red"
		accent  = "teal"
	
	[params.font]
		text = "Ubuntu"
		code = "Ubuntu Mono"

[social]
	twitter = ""
	github  = "skyao"
	email   = "aoxiaojian@gmail.com"


[[menu.main]]
	name   = "前言"
	url    = "/"
	weight = 1

[[menu.main]]
	name   = "介绍"
	identifier = "introduction"
	url    = "/introduction/"
	weight = 100

[[menu.main]]
	name   = "安装"
	identifier = "installation"
	url    = "/installation/"
	weight = 300

[[menu.main]]
	name   = "语法"
	identifier = "grammar"
	url    = "/grammar/"
	weight = 400

[[menu.main]]
	name   = "基础语法"
	identifier = "grammar-basic"
	parent = "grammar"
	url    = "/grammar/basic/"
	weight = 410

[[menu.main]]
	name   = "控制流程"
	identifier = "grammar-flow"
	parent = "grammar"
	url    = "/grammar/flow/"
	weight = 430

[[menu.main]]
	name   = "类型"
	identifier = "grammar-type"
	parent = "grammar"
	url    = "/grammar/type/"
	weight = 450

[[menu.main]]
	name   = "标准库"
	identifier = "stdlib"
	url    = "/stdlib/"
	weight = 600

[[menu.main]]
	name   = "sync"
	identifier = "stdlib-sync"
	parent = "stdlib"
	url    = "/stdlib/sync/"
	weight = 610

[[menu.main]]
	name   = "unsafe"
	identifier = "stdlib-unsafe"
	parent = "stdlib"
	url    = "/stdlib/unsafe/"
	weight = 780

[[menu.main]]
	name   = "工具"
	identifier = "tool"
	url    = "/tool/"
	weight = 2000

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true